# Generated by Django 3.1 on 2020-08-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mentor',
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ManyToManyField(help_text='Enter the names of the mentors of this course.', to='hrm.mentor'),
        ),
    ]
