# Generated by Django 3.1 on 2020-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20200808_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='./photos'),
        ),
    ]
