# Generated by Django 3.1 on 2020-08-08 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20200808_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
